### PR TITLE
Various changes for issues I found while poking around current site

### PR DESCRIPTION
**Pull request by reedloden**
* Update links from http:// to https:// where possible
* Replace 'ruby-advisory-db' with '_advisories' in Jekyll exclusion list
* Fix two config errors (highlighter and atom.xml layout)
* Enable DNT for Twitter share button
* Remove unused modernizr JS
* Add basic Gemfile
* Use correct filter for stripping URL protocol

### CODE REVIEW

**Comment by phillmv** [comment]
Cool. I been following all the stuff you been posting, just been waiting for a spare moment to review it - Looking like Tuesday at the moment.

**Comment by reedloden** [comment]
Cool, looking forward to it. I've kinda been on a Ruby security rampage over the last few days, submitting PRs to at least four different Ruby projects to get them to fix various security (mostly use of TLS) things. Kinda ridiculous the amount of stuff that still uses http:// for downloading critical files. :(

**Comment by tarcieri** [comment]
@reedloden the really fun part is how many SSL/TLS client libraries actually get things like hostname verification correct

**Comment by reedloden** [comment]
@tarcieri, hah, true, but at least those are getting slowly fixed in that regard. One day...

**Pull request merged**
